name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.2.1
  latlong2: ^0.9.0
  image_picker: ^1.0.7
  geolocator: ^11.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_map_cancellable_tile_provider: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
